name: Publish NuGet Package to NuGet.org

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Bump version
        id: version-bump
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"

      - name: Check if version already exists on NuGet.org
        id: check-nuget
        run: |
          version="${{ steps.version-bump.outputs.version }}"
          package="AlphaFeatureToggler"
          exists=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://api.nuget.org/v3-flatcontainer/${package,,}/${version}/${package,,}.${version}.nupkg")

          if [ "$exists" == "200" ]; then
            echo "Version $version already exists on NuGet.org"
            exit 1
          else
            echo "Version $version does not exist. Proceeding..."
          fi

      - name: Update version in .csproj
        run: |
          version="${{ steps.version-bump.outputs.version }}"
          sed -i "s|<Version>.*</Version>|<Version>$version</Version>|" src/AlphaFeatureToggler/AlphaFeatureToggler.csproj

      - name: Update CHANGELOG.md
        run: |
          version="${{ steps.version-bump.outputs.version }}"
          date=$(date +%Y-%m-%d)
          echo -e "## [$version] - $date\n\n$(git log --pretty=format:'- %s' $(git describe --tags --abbrev=0)..HEAD)\n\n$(cat CHANGELOG.md)" > CHANGELOG.md

      - name: Restore dependencies
        run: dotnet restore AlphaFeatureToggler.sln

      - name: Build
        run: dotnet build AlphaFeatureToggler.sln --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack src/AlphaFeatureToggler/AlphaFeatureToggler.csproj --configuration Release --no-build --output ./nupkg

      - name: Create Git Tag
        run: |
          version="${{ steps.version-bump.outputs.version }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add CHANGELOG.md src/AlphaFeatureToggler/AlphaFeatureToggler.csproj
          git commit -m "chore: bump version to $version"
          git tag -a "v$version" -m "Release v$version"
          git push origin "v$version"
          git push

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
