name: Publish NuGet Package to NuGet.org

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore AlphaFeatureToggler.sln

      - name: Build
        run: dotnet build AlphaFeatureToggler.sln --configuration Release --no-restore

      - name: Bump version
        id: version-bump
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: 'v'
          major_pattern: 'BREAKING CHANGE:'
          minor_pattern: 'feat:'
          patch_pattern: 'fix:'
          format: 'v${major}.${minor}.${patch}'

      - name: Update .csproj version
        run: |
          version=$(echo "${{ steps.version-bump.outputs.version }}" | sed 's/^v//')
          sed -i 's|<Version>.*</Version>|<Version>'"$version"'</Version>|' src/AlphaFeatureToggler/AlphaFeatureToggler.csproj
        shell: bash

      - name: Pack NuGet package
        run: dotnet pack src/AlphaFeatureToggler/AlphaFeatureToggler.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
